CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ip TEXT NOT NULL,
  user TEXT NOT NULL,
  source TEXT NOT NULL,
  timestamp DATETIME NOT NULL,
  raw_data TEXT NOT NULL
);
